# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmux < Formula
  desc "See every running process in your browser"
  homepage "https://gmux.app"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.2.2/gmux_0.2.2_darwin_amd64.zip"
      sha256 "dcf8423edba02a12df0b15b8fbf9d47e5fe4e89705de27d166df25e34d6b387b"

      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.2.2/gmux_0.2.2_darwin_arm64.zip"
      sha256 "03b7e5eedc668726ffe9abe506b0b07f37fcd0144d12c2562191a773a57e81e1"

      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.2.2/gmux_0.2.2_linux_amd64.tar.gz"
      sha256 "31abbc642af773316e11d07ee748a72362b1265f532ad5a593d83c43b27b9ca8"
      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.2.2/gmux_0.2.2_linux_arm64.tar.gz"
      sha256 "403c53260d438aad0fe33d89e6d718b67cd11dbebab0d54c90141fefbfb5456e"
      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
  end

  def caveats
    <<~EOS
      Launch a session:
        gmux claude           # coding agent
        gmux pytest -x        # test runner
        gmux make build       # any command

      Open the dashboard:
        open http://localhost:8790
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/gmux --version")
  end
end
