# This file was generated by GoReleaser. DO NOT EDIT.
cask "gmux" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "285aa16c8ce5de998fcc3bc1d18558fac95002f5d157bffcfe6ca83d61d1e6c3"
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "2c39345ec08600ff70479044013288a996cc0fcd20e4e1276e2800a07a7c7df1"
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "158d023fa32518c4329c8708ed24fdd2d3cb62c372cc6ec4782b4e064398d3e1"
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a438cdcbc6b59fe3c22a74f950268f0f0e1ef068b3a853556b0291cfcc3c92d0"
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gmux"
  desc "See every running process in your browser"
  homepage "https://gmux.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gmux"
  binary "gmuxd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gmux"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gmuxd"]
    end
    # Seamless daemon upgrade: if a daemon was running, restart it with
    # the new version. If it wasn't running, do nothing — the next
    # `gmux` invocation will start it on demand.
    system_command "/bin/sh", args: ["-c", <<~EOS
      if "#{staged_path}/gmuxd" status >/dev/null 2>&1; then
        "#{staged_path}/gmuxd" start
      fi
    EOS
    ]
  end

  # No zap stanza required

end
