# This file was generated by GoReleaser. DO NOT EDIT.
cask "gmux" do
  name "gmux"
  desc "See every running process in your browser"
  homepage "https://gmux.app"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gmux"
  binary "gmuxd"

  on_macos do
    on_intel do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_darwin_amd64.zip"
      sha256 "27ab96ee40959b7918e8f808f0e24fe4b8b0e85d8597a1c883d349c6a891dd6e"
    end
    on_arm do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_darwin_arm64.zip"
      sha256 "1cb6137efde8571728192a29b113f123c4cbac4413563ac199f6a0d15b9f6f53"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_linux_amd64.tar.gz"
      sha256 "e07584a968a1a78092552a614a8402e986352e3222e8ffb5cba130a318e9b0ef"
    end
    on_arm do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_linux_arm64.tar.gz"
      sha256 "77f6bae39f2102ee958f10741e43940416023fc129b29e14064f5930cd9ba911"
    end
  end

  caveats do
    "Launch a session:"
    "  gmux claude           # coding agent"
    "  gmux pytest -x        # test runner"
    "  gmux make build       # any command"
    ""
    "Open the dashboard:"
    "  open http://localhost:8790"
  end

  # No zap stanza required
end
