# This file was generated by GoReleaser. DO NOT EDIT.
cask "gmux" do
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_darwin_amd64.zip"
      sha256 "6336e2e51b6e722d45925441a8aa1cfc290b8a3cd4aff27af309df3862a56c44"
    end
    on_arm do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_darwin_arm64.zip"
      sha256 "50500bbbfc8e0e3d701950393420416dc1c07f0b43e42c5012a2631d4654c462"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_linux_amd64.tar.gz"
      sha256 "aaf1c6dc3195de24ebd39f4ff3d8709a1286d857ffef617efa89765bee04b7f6"
    end
    on_arm do
      url "https://github.com/gmuxapp/gmux/releases/download/v#{version}/gmux_#{version}_linux_arm64.tar.gz"
      sha256 "7ea241554f9d47599becde9928a234336888526ddf0eea48696d726808138957"
    end
  end

  name "gmux"
  desc "See every running process in your browser"
  homepage "https://gmux.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gmux"
  binary "gmuxd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gmux"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gmuxd"]
    end
    # Seamless daemon upgrade: if a daemon was running, shut it down and
    # immediately start the new version. If it wasn't running, do nothing —
    # the next `gmux` invocation will start it on demand.
    system_command "/bin/sh", args: ["-c", <<~EOS
      if curl -sf -o /dev/null http://localhost:8790/v1/health 2>/dev/null; then
        "#{staged_path}/gmuxd" shutdown
        nohup "#{staged_path}/gmuxd" start </dev/null >/dev/null 2>&1 &
      fi
    EOS
    ]
  end

  # No zap stanza required

end
