# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmux < Formula
  desc "Terminal session orchestration — manage AI agents, test runners, and long-running processes from your browser"
  homepage "https://github.com/gmuxapp/gmux"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.1.0/gmux_0.1.0_darwin_amd64.zip"
      sha256 "f0e52019c267a665d0729994d8070952bed3d732fbe3fcf1c2ebafc4f904ff75"

      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.1.0/gmux_0.1.0_darwin_arm64.zip"
      sha256 "ee7e4f717c76b3bc7803505a35daeb6aeeb52a7ab30816aac3758161313583c5"

      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.1.0/gmux_0.1.0_linux_amd64.tar.gz"
      sha256 "d9938fe574412f0512845f749e52ddbe55afd292a19246b68658a6261b5f53e2"
      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gmuxapp/gmux/releases/download/v0.1.0/gmux_0.1.0_linux_arm64.tar.gz"
      sha256 "1edbf5d57a176cc838d6b9055f7d66403476507da5d347743b80c52a930b7e72"
      define_method(:install) do
        bin.install "gmux"
        bin.install "gmuxd"
      end
    end
  end

  def caveats
    <<~EOS
      Open the UI:
        gmux

      Launch a session:
        gmux pi              # coding agent
        gmux pytest -x       # test runner
        gmux make build      # any command
    EOS
  end
end
